# Makefile
# See https://docs.cocotb.org/en/stable/quickstart.html for more info

# defaults
SIM ?= icarus
FST ?= -fst # Use more efficient FST format
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
PROJECT_SOURCES  = project.v
PROJECT_SOURCES += fcc_core.v
PROJECT_SOURCES += fcc_fixpt.v
PROJECT_SOURCES += ps_pwm.v
PROJECT_SOURCES += signal_generator_0phase.v
PROJECT_SOURCES += signal_generator_180phase.v
PROJECT_SOURCES += comparator.v
PROJECT_SOURCES += dead_time_generator.v
PROJECT_SOURCES += timer_control.v
PROJECT_SOURCES += adc.v
PROJECT_SOURCES += i2c.v
PROJECT_SOURCES += uart.v
PROJECT_SOURCES += screen.v
PROJECT_SOURCES += text.v
PROJECT_SOURCES += font_rom.v
PROJECT_SOURCES += toDec.v
PROJECT_SOURCES += div_u32.v

ifneq ($(GATES),yes)

# RTL simulation:
SIM_BUILD				= sim_build/rtl
VERILOG_SOURCES += $(addprefix $(SRC_DIR)/,$(PROJECT_SOURCES))

else

# Gate level simulation:
SIM_BUILD				= sim_build/gl
COMPILE_ARGS    += -DGL_TEST
COMPILE_ARGS    += -DFUNCTIONAL
COMPILE_ARGS    += -DSIM
VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v
VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v

# this gets copied in by the GDS action workflow
VERILOG_SOURCES += $(PWD)/gate_level_netlist.v

endif

# Allow sharing configuration between design and testbench via `include`:
COMPILE_ARGS 		+= -I$(SRC_DIR)

# Include the testbench sources:
VERILOG_SOURCES += $(PWD)/tb.v
TOPLEVEL = tb

# List test modules to run, separated by commas and without the .py suffix:
COCOTB_TEST_MODULES = test

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
